### ISSUE TITLE
Some code blocks are not rendering correctly

### ISSUE THREAD

**Issue by kgilden** [knpuniversity/gulp#2]
Yo!

Looks like _some_ code blocks are not rendering for the gulp tutorial. Both FF and Chrome seem to be affected. Check out the screenshot below:

![screenshot - 04082015 - 04 56 55 pm](https://cloud.githubusercontent.com/assets/918599/7046721/7c38a850-de10-11e4-9a5f-4af2537bacb8.png)

Cheers,
Kristen

**Comment by weaverryan** [comment]
Boom! All better, thanks to you pointing it out! http://knpuniversity.com/screencast/gulp/minify-only-production

When you click the little arrows, you can load more lines. And the cache keys for that request were colliding with the cache keys for the whole code block :).

Thanks Duke! We miss you!
